<a href="https://colab.research.google.com/github/Mohanee28/06July2024/blob/main/LDA%20Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/nba_final.csv')

In [ ]:
df.head()

,Rk,Player.x,Player_ID,Pos1,Pos2,Age,Tm,G,GS,MP,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,A.J. Hammons,hammoaj01,C,NaN,24,DAL,22,0,7.4,...,West,Front,786,123,NaN,NaN,NaN,NaN,83.5,No
1,58,Aaron Brooks,brookaa01,PG,NaN,32,IND,65,0,13.8,...,Est,Back,2474,64,NaN,NaN,NaN,NaN,48.2,No
2,157,Aaron Gordon,gordoaa01,SF,NaN,21,ORL,80,72,28.7,...,Est,Front,22774,29,NaN,NaN,NaN,NaN,40.0,No
3,352,Adreian Payne,paynead01,PF,NaN,25,MIN,18,0,7.5,...,West,Front,861,120,1.0,52.0,NaN,NaN,75.5,No
4,10,Al-Farouq Aminu,aminual01,PF,NaN,26,POR,61,25,29.1,...,West,Front,4971,69,7.0,23.0,NaN,NaN,42.8,No

In [ ]:
df.columns

Index(['Rk', 'Player.x', 'Player_ID', 'Pos1', 'Pos2', 'Age', 'Tm', 'G', 'GS',
       'MP', 'FG', 'FGA', 'FG.', 'X3P', 'X3PA', 'X3P.', 'X2P', 'X2PA', 'X2P.',
       'eFG.', 'FT', 'FTA', 'FT.', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
       'TOV', 'PF', 'PTS', 'Salary', 'mean_views', 'Season', 'Conference',
       'Role', 'Fvot', 'FRank', 'Pvot', 'PRank', 'Mvot', 'MRank', 'Score',
       'Play'],
      dtype='object')

In [ ]:
df.shape

(1408, 45)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1408 entries, 0 to 1407
Data columns (total 45 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rk          1408 non-null   int64
 1   Player.x    1408 non-null   object
 2   Player_ID   1408 non-null   object
 3   Pos1        1408 non-null   object
 4   Pos2        12 non-null     object
 5   Age         1408 non-null   int64
 6   Tm          1408 non-null   object
 7   G           1408 non-null   int64
 8   GS          1408 non-null   int64
 9   MP          1408 non-null   float64
 10  FG          1408 non-null   float64
 11  FGA         1408 non-null   float64
 12  FG.         1404 non-null   float64
 13  X3P         1408 non-null   float64
 14  X3PA        1408 non-null   float64
 15  X3P.        1309 non-null   float64
 16  X2P         1408 non-null   float64
 17  X2PA        1408 non-null   float64
 18  X2P.        1393 non-null   float64
 19  eFG.        1404 non-null   float64
 20  FT          1408 non-null   float64
 21  FTA         1408 non-null   float64
 22  FT.         1361 non-null   float64
 23  ORB         1408 non-null   float64
 24  DRB         1408 non-null   float64
 25  TRB         1408 non-null   float64
 26  AST         1408 non-null   float64
 27  STL         1408 non-null   float64
 28  BLK         1408 non-null   float64
 29  TOV         1408 non-null   float64
 30  PF          1408 non-null   float64
 31  PTS         1408 non-null   float64
 32  Salary      1346 non-null   float64
 33  mean_views  1270 non-null   float64
 34  Season      1408 non-null   object
 35  Conference  1408 non-null   object
 36  Role        1408 non-null   object
 37  Fvot        1408 non-null   int64
 38  FRank       1408 non-null   int64
 39  Pvot        1249 non-null   float64
 40  PRank       1249 non-null   float64
 41  Mvot        1004 non-null   float64
 42  MRank       1004 non-null   float64
 43  Score       1408 non-null   float64
 44  Play        1408 non-null   object
dtypes: float64(30), int64(6), object(9)
memory usage: 495.1+ KB

In [ ]:
df.notnull().sum()

Rk            1408
Player.x      1408
Player_ID     1408
Pos1          1408
Pos2            12
Age           1408
Tm            1408
G             1408
GS            1408
MP            1408
FG            1408
FGA           1408
FG.           1404
X3P           1408
X3PA          1408
X3P.          1309
X2P           1408
X2PA          1408
X2P.          1393
eFG.          1404
FT            1408
FTA           1408
FT.           1361
ORB           1408
DRB           1408
TRB           1408
AST           1408
STL           1408
BLK           1408
TOV           1408
PF            1408
PTS           1408
Salary        1346
mean_views    1270
Season        1408
Conference    1408
Role          1408
Fvot          1408
FRank         1408
Pvot          1249
PRank         1249
Mvot          1004
MRank         1004
Score         1408
Play          1408
dtype: int64

In [ ]:
df.notna().sum()

Rk            1408
Player.x      1408
Player_ID     1408
Pos1          1408
Pos2            12
Age           1408
Tm            1408
G             1408
GS            1408
MP            1408
FG            1408
FGA           1408
FG.           1404
X3P           1408
X3PA          1408
X3P.          1309
X2P           1408
X2PA          1408
X2P.          1393
eFG.          1404
FT            1408
FTA           1408
FT.           1361
ORB           1408
DRB           1408
TRB           1408
AST           1408
STL           1408
BLK           1408
TOV           1408
PF            1408
PTS           1408
Salary        1346
mean_views    1270
Season        1408
Conference    1408
Role          1408
Fvot          1408
FRank         1408
Pvot          1249
PRank         1249
Mvot          1004
MRank         1004
Score         1408
Play          1408
dtype: int64

In [ ]:
df.isnull().sum()

Rk               0
Player.x         0
Player_ID        0
Pos1             0
Pos2          1396
Age              0
Tm               0
G                0
GS               0
MP               0
FG               0
FGA              0
FG.              4
X3P              0
X3PA             0
X3P.            99
X2P              0
X2PA             0
X2P.            15
eFG.             4
FT               0
FTA              0
FT.             47
ORB              0
DRB              0
TRB              0
AST              0
STL              0
BLK              0
TOV              0
PF               0
PTS              0
Salary          62
mean_views     138
Season           0
Conference       0
Role             0
Fvot             0
FRank            0
Pvot           159
PRank          159
Mvot           404
MRank          404
Score            0
Play             0
dtype: int64

In [ ]:
df['Pos2'] = df['Pos2'].replace(np.nan, 'NONE')
df['Pos2'].unique()

array(['NONE', 'C', 'SG', 'SF', 'PF'], dtype=object)

In [ ]:
df['Pos2'].value_counts()

Pos2
NONE    1396
SG         5
SF         3
C          2
PF         2
Name: count, dtype: int64

In [ ]:
df = df.fillna(0)

In [ ]:
df.isnull().sum()

Rk            0
Player.x      0
Player_ID     0
Pos1          0
Pos2          0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG.           0
X3P           0
X3PA          0
X3P.          0
X2P           0
X2PA          0
X2P.          0
eFG.          0
FT            0
FTA           0
FT.           0
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Salary        0
mean_views    0
Season        0
Conference    0
Role          0
Fvot          0
FRank         0
Pvot          0
PRank         0
Mvot          0
MRank         0
Score         0
Play          0
dtype: int64

In [ ]:
!pip install sweetviz

Requirement already satisfied: sweetviz in /usr/local/lib/python3.12/dist-packages (2.3.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (2.1.4)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (1.26.4)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (3.7.5)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (1.11.4)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib-resources>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from sweetviz) (6.5.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.11.1->sweetviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.61.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (25.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)

In [ ]:
if not hasattr(np, 'VisibleDeprecationWarning'):
    np.VisibleDeprecationWarning = type('VisibleDeprecationWarning', (DeprecationWarning,), {})

In [ ]:
import sweetviz as sv
report = sv.analyze(df)
report.show_html('Report.html')

                                             |          | [  0%]   00:00 -> (? left)

Report Report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [ ]:
df = df.drop(['Player.x', 'Player_ID'], axis=1)

In [ ]:
df.shape

(1408, 43)

In [ ]:
df.describe()

,Rk,Age,G,GS,MP,FG,FGA,FG.,X3P,X3PA,...,PTS,Salary,mean_views,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score
count,1408.000000,1408.000000,1408.000000,1408.000000,1408.000000,1408.000000,1408.000000,1408.000000,1408.000000,1408.000000,...,1408.000000,1.408000e+03,1408.000000,1.408000e+03,1408.000000,1408.000000,1408.000000,1408.000000,1408.000000,1408.000000
mean,257.701705,26.139205,54.099432,25.906960,20.162713,3.262429,7.173153,0.446332,0.856250,2.420810,...,8.794176,6.491055e+06,891.888404,1.176963e+05,61.595170,7.216619,38.385653,2.095170,5.098011,75.578338
std,150.765855,4.282550,24.052508,28.664578,9.066041,2.181694,4.591826,0.094679,0.792307,2.061737,...,6.081955,7.418582e+06,2045.319335,4.286272e+05,36.681104,25.022761,26.005078,12.607836,3.473575,41.404980
min,1.000000,19.000000,1.000000,0.000000,0.700000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,3.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,127.000000,23.000000,36.000000,1.000000,13.300000,1.600000,3.700000,0.403000,0.200000,0.700000,...,4.300000,1.349936e+06,127.477397,2.135500e+03,30.000000,0.000000,16.000000,0.000000,0.000000,45.000000
50%,257.000000,25.000000,62.000000,13.000000,20.000000,2.800000,6.150000,0.443000,0.700000,2.050000,...,7.300000,3.127094e+06,360.994521,6.843000e+03,60.000000,1.000000,39.000000,0.000000,7.000000,69.900000
75%,385.250000,29.000000,74.000000,52.000000,27.500000,4.500000,9.900000,0.490000,1.300000,3.700000,...,12.000000,9.904495e+06,848.902740,2.925250e+04,90.250000,3.000000,60.000000,0.000000,8.000000,109.200000
max,540.000000,42.000000,82.000000,82.000000,37.800000,10.800000,24.500000,1.000000,5.100000,13.200000,...,36.100000,3.745715e+07,34147.961644,4.620809e+06,145.000000,269.000000,88.000000,100.000000,9.000000,166.800000

In [ ]:
df.describe(include='O')

        Pos1  Pos2    Tm   Season Conference   Role  Play
count   1408  1408  1408     1408       1408   1408  1408
unique     5     5    30        3          2      2     2
top       SG  NONE   MIL  2017-18       West  Front    No
freq     324  1396    51      498        704    779  1335

In [ ]:
obj_col = ['Pos1', 'Pos2', 'Tm', 'Season', 'Conference', 'Role', 'Play']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
Le = LabelEncoder()

In [ ]:
for i in obj_col:
  df[i] = Le.fit_transform(df[i])
print(obj_col)

['Pos1', 'Pos2', 'Tm', 'Season', 'Conference', 'Role', 'Play']

In [ ]:
df.head()

,Rk,Pos1,Pos2,Age,Tm,G,GS,MP,FG,FGA,...,Conference,Role,Fvot,FRank,Pvot,PRank,Mvot,MRank,Score,Play
0,170,0,1,24,6,22,0,7.4,0.8,1.9,...,1,1,786,123,0.0,0.0,0.0,0.0,83.5,0
1,58,2,1,32,11,65,0,13.8,1.9,4.6,...,0,0,2474,64,0.0,0.0,0.0,0.0,48.2,0
2,157,3,1,21,21,80,72,28.7,4.9,10.8,...,0,1,22774,29,0.0,0.0,0.0,0.0,40.0,0
3,352,1,1,25,17,18,0,7.5,1.3,3.0,...,1,1,861,120,1.0,52.0,0.0,0.0,75.5,0
4,10,1,1,26,24,61,25,29.1,3.0,7.6,...,1,1,4971,69,7.0,23.0,0.0,0.0,42.8,0

In [ ]:
##def encode_cat_col (dataframe, columns):
  ##data_frame = dataframe.copy()
  ##le=LabelEncoder()
  ##for col in columns:
    ##data_frame[col] = le.fit_transform(data_frame[col].astype(str))
  ##return data_frame

In [ ]:
##df = encode_cat_col(df, obj_col)

In [ ]:
x = df.drop(['Play'], axis = 1)
y = df['Play']

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x = sc.fit_transform(x)

In [ ]:
print(x)

[[-0.58191469 -1.40108842 -0.07184075 ... -0.16623906 -1.46817686
   0.19138945]
 [-1.32505241 -0.01428174 -0.07184075 ... -0.16623906 -1.46817686
  -0.66146791]
 [-0.66817174  0.67912159 -0.07184075 ... -0.16623906 -1.46817686
  -0.85958209]
 ...
 [ 0.33373715  1.37252493 -0.07184075 ... -0.16623906  0.83574403
   1.36799438]
 [ 0.8977256  -1.40108842 -0.07184075 ... -0.16623906  0.54775392
  -0.13960618]
 [ 1.32237572  1.37252493 -0.07184075 ... -0.16623906  0.83574403
   1.09256735]]

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [ ]:
LDA = LinearDiscriminantAnalysis(n_components=1)

In [ ]:
X = LDA.fit_transform(x,y)

In [ ]:
X.shape

(1408, 1)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 30)

In [ ]:
print(x_train.shape)
print(x_test.shape)

(1126, 42)
(282, 42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lg = LogisticRegression()

In [ ]:
lg.fit(x_train, y_train)

LogisticRegression()

In [ ]:
lg_prid = lg.predict(x_test)

In [ ]:
from sklearn.metrics import *

In [ ]:
accuracy_scor = accuracy_score(lg_prid, y_test)

In [ ]:
print(accuracy_scor)

0.9893617021276596

In [ ]:
print('r2_score:', round(r2_score(lg_prid,y_test),4))

r2_score: 0.7581

In [ ]:
print('MSE:', round(mean_squared_error(lg_prid, y_test), 4))

MSE: 0.0106

In [ ]:
print('MOE:', round(mean_absolute_error(lg_prid, y_test), 4))

MOE: 0.0106

In [ ]:
!pip install pycaret

In [ ]:
from pycaret.class import *